FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src
COPY test ./test

RUN npm run build

CMD ["node", "--test", "--test-reporter=spec", "--test-timeout=180000", "dist/test/integration/delay.test.js"]
