global:
  scrape_interval: 5s

scrape_configs:
  - job_name: pubsub-delay
    metrics_path: /metrics
    static_configs:
      - targets: ['bounded-pool:8080']
        labels:
          service: bounded-pool
      - targets: ['time-wheel:8080']
        labels:
          service: time-wheel
